# Spring Boot
server:
  port: 8080
logging:
  path: C:\Users\serg\Desktop\quotesStorage\logs
# Database
database:
  schema-name: QUOTES
  path: C:\Users\serg\.quotes_store\data
# Client
client:
  type: simple
  symbols:
  - ETHTUSD
  - SNTBTC
  - BCNETH