# Spring Boot
server:
  port: 8080
logging:
  path: ${user.home}\.quotes_store\logs
# Database
database:
  schema-name: QUOTES
  path: ${user.home}\.quotes_store\data
# Client
client:
  type: simple
  symbols:
  - BTCUSDT